### ISSUE TITLE
Proposal missing a lot of important stuff

### ISSUE THREAD

**Issue by jeffnv** [McMenemy/optimyze#1]
Wireframes
React Components
Flux Stores
API endpoints
DB schema

planning all these in a advance will be tremendously helpful to your development process. You MUST do these in advance.

**Comment by jeffnv** [comment]
nvm they are in DOCS add a link to the readme please

**Comment by McMenemy** [comment]
Sorry, I realized I broke the links at some point and re-added them in a little late.
