### ISSUE TITLE
api endpoints

### ISSUE THREAD

**Issue by jeffnv** [McMenemy/optimyze#2]
```
GET /api/optimizations/:user_id
returns all optimizations for current user
```

This conflicts with the show route for optimizations. Make the index receive a query string instead.

Also, what about categories? Don't we need more API endpoints for categories? I don't think this is a complete list.

**Comment by McMenemy** [comment]
Good call about the query string, I'll do that.

I was planing to use the has many relationship between optimizations and categories along with jbuilder to always retrieve categories along with optimizations.
